### ISSUE TITLE
[tie] missing features/bugs

### ISSUE THREAD

**Issue by water111** [water111/jak-project#1028]
- [ ] there's no wind effect
- [ ] there is something wrong with the maps on the wall in sandover and they don't appear.  I suspect there's a blending issue.
- [ ] missing railings on the bridges (I swear this worked at some point)
- [ ] missing leaves on small trees. (should check if the leaves are rendered with tie/shrub)
- [ ] walls of citadel elevator "flicker"
- [ ] figure out flags field of `InstanceTie`
- [ ] remove redundant visgroups

Many of the missing things seem like a alpha test issue

**Comment by ManDude** [comment]
also the railings on the bridges
![image](https://user-images.githubusercontent.com/7569514/147419020-85ee25c2-bb61-40d2-a0ca-b939280d008c.png)
the leaves on the small palms
![image](https://user-images.githubusercontent.com/7569514/147419034-3cf2e19b-77f5-43f2-a922-35c2bbb9b37b.png)

**Comment by water111** [comment]
I still need to check in a 128MB PCSX2 build, but I think a lot of these are actually rendered with shrub.

I'm not sure what the citadel thing is yet, but it might be an issue with using TIE instead of generic.

**Comment by ManDude** [comment]
Just checked and you're right, the railings and palms are part of "shrubbery".
