### ISSUE TITLE
[decomp] negative values are not handled correctly with bitfields

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#1029]
> WARN: Expression building failed: In darkecobarrel-mover-pos: Failed to decompile bitfield enum draw-status. Original value is 0xffffffffffffffdf but we could only make 0xdf using the available fields.

```asm
    addiu v1, r0, -33         ;; [132] (set! v1-34 -33) [] -> [v1: <integer -33> ]
    lwu a0, 116(s6)           ;; [133] (set! a0-18 (l.wu (+ self 116))) [s6: darkecobarrel-mover ] -> [a0: draw-control ]
    lbu a0, 0(a0)             ;; [134] (set! a0-19 (l.bu a0-18)) [a0: draw-control ] -> [a0: draw-status ]
    and v0, v1, a0            ;; [135] (set! v0-14 (logand (the-as uint v1-34) a0-19))
                              ;; [v1: uint a0: draw-status ] -> [v0: uint ]
    lwu v1, 116(s6)           ;; [136] (set! v1-35 (l.wu (+ self 116))) [s6: darkecobarrel-mover ] -> [v1: draw-control ]
    sb v0, 0(v1)              ;; [137] (s.b! v1-35 v0-14) [v0: uint v1: draw-control ] -> []
```

For some reason they use `-33` here as a shorthand to generate a mask of `1101 1111` but the decompiler assumes the full 64bit number is needed.  It's not factoring in the size of the bitfield.

**Comment by water111** [comment]
Sorry, I think my comments earlier were totally wrong.  The problem isn't the negative/64-bit thing, it's that the decompiler isn't recognizing this as _clearing_ a bit.  If that fails it tries to cast the mask directly to the enum type and that doesn't work.  

The detection for clearing a bit should happen in `SimpleExpressionElement::update_from_stack_logor_or_logand_helper`. We should hit line 1577 (`// clearing a bitfield.`).  If we get here, we know it's a mask and we do:
```
decompile_bitfield_enum_from_int(arg1_type, env.dts->ts, ~*integer);
```
which I think we are not hitting. That line does `~value` which should give us `~0xffffffffffffffdf = 0x20`, which doesn't match the error.

**Comment by ManDude** [comment]
it happens here:

```lisp
    (else
      (set! v0-14 (logand (the-as uint -33) (-> self draw status)))
      (set! (-> self draw status) v0-14)
      )
    )
  v0-14
```
I think the decompiler wants to reuse `v0-14` so it can't collapse the full enum bit clear operation.
