### ISSUE TITLE
[vis] does not work properly

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#1085]
Visibility doesn't seem to work properly right now. Every actor and all of the scenery is visible when that shouldn't be the case.

**Comment by water111** [comment]
visibility for actors fixed and visibility for tie/tfrag added in https://github.com/water111/jak-project/pull/1100. Actor heap memory is a lot lower. Visibility seems to be working (has the same bugs as PS2 version) and the triangle count goes down in places you'd expect.
