### ISSUE TITLE
Remove SystemThread's preformance stats

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#18]

**Comment by water111** [comment]
I'd say remove. These are the threads we have now:
- IOP, which actually goes and starts a bunch of threads, but only one runs at a time (managed by `IOPKernel`)
- DECI2/DMP, which handles the Listener network connection
- EE, the main thread (PS2 has only one main CPU core). Runs all GOAL.

I'd expect only the EE thread to use much CPU, so the performance statistics are kinda useless.  Eventually we'll run the equivalent of VU1 in a separate thread but I think measuring "how long does it take to complete one frame" is a more useful performance metric than CPU utilization.
