### ISSUE TITLE
[Decompiler] Support OpenGOAL vector operations for `vector`

### ISSUE THREAD

**Issue by water111** [water111/jak-project#240]
We should implement a decompiler pass to rewrite PS2 VU0 macro mode vector instructions into a form supported by OpenGOAL. I think we should focus on the `vector.gc` file as a starting point.

I think we may eventually want to replace simple sequences of vector instructions, so the pass should support looking at sequences of instructions that always execute consecutively.  For example, `vopmula` and `vopmsub` always appear in sequences and could possibly be replaced with a single instruction.

## Setting up a new pass
The main IR2 analysis runs from `ObjectFileDB::analyze_functions()` in `ObjectFileDB_IR2.cpp`.  There are a bunch of passes and you can add one that's similar to `ir2_build_expressions`.  Each pass uses `for_each_function_def_order` to iterate through all functions. I would copy the setup used for `ir2_build_expressions` and `convert_to_expressions`. Put your analysis pass in a new file in the `analysis` folder.  Have the pass run after `ir2_build_expressions`.

## `Form*` and `FormElement*`
A `FormElement*` is a Lisp form. A `Form*` is a list of `FormElement*`s that run in sequence. A `Form*` with exactly one `FormElement*` is a transparent wrapper around that `FormElement*`. For example, if you have a `FormElement*` of `(+ 1 2)` and put that into a `Form*`, the `Form` will also be `(+ 1 2)`.

If you put multiple `FormElement*`s into a form, it automatically becomes a begin. For example, if you put `(+ 1 2)` and `(+ 2 4)` into a `Form*`, you get:
```
(begin
  (+ 1 2)
  (+ 2 4)
  )
```
which means that you do `(+ 1 2)`, and then you do `(+ 2 4)`.

## Rewriting ops
Inside the analysis pass function, you can iterate over all `Form`s with
```cpp
top_level->apply_form([&](Form* form) {
   form->elts() // this is a list of FormElement*s that always execute in sequence.
});
```

To determine if a `FormElement*` is an assembly operation:
- Try a `dynamic_cast` to an `AsmOpElement`. The `AsmOpElement` stores an `AsmOp`. 
- Look at the `Instruction`'s `kind` in the `AsmOp`.

If you want to rewrite, you can replace the `AsmOpElement*` with a different element.
I'd recommend making your own child class of `FormElement` for this. Note that you should create new `FormElement`s with `pool.alloc_element`.

## Representing a rewritten operation.
There are two challenges here:

First, you'll need a way to store the name of the operation. This could just be a string, or you could go for something more complicated.

Second, you'll need a way to store the operands.   

For storing a `vf` register, ACC, or Q I would use a `InstructionAtom`. It can store a register for the `vf` registers, or it can store `VU_ACC` or `VU_Q`.  NOTE: the `Q` and `R` registers defined in `Vi` under `Register` are _not_ the same as the `VU_ACC` or `VU_Q` - they represent accessing these registers through the COP integer registers, which is not what we are doing. Use `VU_ACC` and `VU_Q`.

You may also need to store a general purpose register for instructions like `.lvf`. For these, you should use a `Variable`. This is how they are stored in an `AsmOp`.  A `Variable` is just a register which also knows "when" it is accessed. It can print itself with a variable name that's determined by the decompilation.

## Stuff for me to do
- Make sure the decompiler runs on code in `vector`
- Implement a check to see if any code relies on values in `vf` registers, the accumulator, or Q,

**Comment by xTVaser** [comment]
Looking into this
