### ISSUE TITLE
Tests didn't run on a PR

### ISSUE THREAD

**Issue by water111** [water111/jak-project#26]
Tests didn't run on https://github.com/water111/jak-project/pull/21
There's a merge conflict, but that didn't seem to prevent tests from running on other PRs.

@xTVaser - any ideas? I'm not sure what's different about this PR.

**Comment by xTVaser** [comment]
Looks like another github actions limitation unfortunately.
The way it creates the branch for the pull_request event cannot be done if there are conflicts - https://github.community/t/run-actions-on-pull-requests-with-merge-conflicts/17104/9

**Comment by water111** [comment]
:+1:
