### ISSUE TITLE
[REPL/Low-Priority] Support auto-completion using linenoise library

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#302]
Linenoise supports tab-completion - https://github.com/antirez/linenoise#completion

It would be pretty awesome if we could maintain a list of the currently loaded functions / commands and allow them to be tab-completed.  This doesn't seem _that_ impossible, but is by no means a priority (we aren't writing code ourselves...yet)

**Comment by water111** [comment]
I agree, it shouldn't be too hard. 

One feature I am planning for the compiler is to have something like
`(find-definition xyz)`
 and it would print out what file/line the thing is defined on, and if its a function, global variable, type, constant, or macro.  These could likely be related - I'll keep this in mind when I get around to adding this and make sure it supports partial names.

**Comment by water111** [comment]
See here for an example of how to get all functions/methods/etc starting with a given prefix.
https://github.com/water111/jak-project/blob/9168f03289b37d4458c9387bc53b6ddfc9eb348c/goalc/compiler/compilation/CompilerControl.cpp#L451
