### ISSUE TITLE
[decompiler] `let` form maker re-uses function argument names if that register is re-used

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#326]
appears in `time-to-ground` (`dynamics-h`)

**Comment by water111** [comment]
The loop/let:
```lisp
   (while (< (- arg2) f0-0)
    (let ((arg0 (- arg0 (* 0.0033333334 arg1)))) ;; should be a set!
     (+! f0-0 (* 0.0033333334 arg0))
     )
```
is actually an incorrect decompilation - the value of the outer `arg0` should update on each iteration of the loop and this should be a single variable.  The variable insertion pass has done this correctly (there is only a single `arg0` variable according to the decompiler).  But the `let` pass put a `let` in a place that doesn't make sense, so there end up being two variables named `arg0` in the final output.

This is actually a fundamental issue with the `insert_lets` pass. The scope of the `let` is decided based on the outer most scope where the variable is referenced, not the scope of where the variable is live.  Getting this information after expressions have been built isn't really possible. So I think this is an equivalent condition:
- If register is dead before the initial `set!`, allow inserting a let.
- If register is live before the initial `set!`, only allow a `let` if the variable in the register is different.

I will try implementing this and see if it can solve this issue.
