### ISSUE TITLE
[OpenGOAL Language] Create a usable manual

### ISSUE THREAD

**Issue by water111** [water111/jak-project#371]
The OpenGOAL "manual" is terrible.  Sometimes I forget exactly how something works, and I have to look at the source code for the compiler to remember. 

Now that the OpenGOAL language isn't changing very much, the manual should be revisited and cleaned up.  It could also have examples from actual decompiled game code.

**Comment by xTVaser** [comment]
I'll try to take a stab at this, I was thinking it would be nice if the config helper tooling I started on was more general purpose -- as in, we could use it for also providing docs and project status.
