### ISSUE TITLE
Create Compiler "Torture Tests"

### ISSUE THREAD

**Issue by water111** [water111/jak-project#43]
To help find bugs in the compiler, I'm imagining we could create a test which has a lot of operations. This would cause more cases in the register allocation code to be tested and increase our confidence that the compile does the right thing. I'm imagining that we could start with these operations:

- `let` to create local variables
- `set!` to change the value of local variables
- Integer Math (+, -,). Lets avoid /, *, and mod until we're sure the current behavior is right. 
- Bitwise operators (logand, logior, logxor, lognot)
- Defining and calling functions which use these things
- Doing these things in strange and interesting orders

One possible approach would be to write a simple script to generate some random large programs.  Figuring out the correct answer might be a little tricky though. If there's no overflows, I think Common Lisp has an almost identical syntax for these operations.

### Reference:
All existing tests are here:
https://github.com/water111/jak-project/tree/master/goal_src/test
A few good example tests that are simple
https://github.com/water111/jak-project/blob/master/goal_src/test/test-div-2.gc
https://github.com/water111/jak-project/blob/master/goal_src/test/test-three-reg-add.gc
https://github.com/water111/jak-project/blob/master/goal_src/test/test-add-function-returns.gc

The code that runs the tests and checks the result is here:
https://github.com/water111/jak-project/blob/master/test/test_compiler_and_runtime.cpp#L178

The list of things the compiler can do is at the top of this file, as the not-commented-out lines of `goal_forms`:
https://github.com/water111/jak-project/blob/master/goalc/compiler/compilation/Atoms.cpp

Some features are implemented as macros here:
https://github.com/water111/jak-project/blob/master/goal_src/goal-lib.gc

**Comment by xTVaser** [comment]
I think I have a decent idea to accomplish this. As you say, we likely won't comprehensively test _everything_ immediately.  But it should be possible to make something that is generic/flexible enough to make adding tests in the future easier.

I'm thinking that with a minimal set of templated GOAL functions, we should be able to generate a large number of tests (including stress tests) fairly easily.  This could be expanded further to exhaustively test various combinations.

I'll take a stab at this.

**Comment by water111** [comment]
Compiler test framework was implemented and used for many tests
