### ISSUE TITLE
[Decompiler] 128-bit bitfield types

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#438]
These are not properly supported. Consider the type `res-tag`:

```lisp
(deftype res-tag (uint128)
  ((name        symbol  :offset 0)
   (key-frame   float   :offset 32)
   (elt-type    type    :offset 64)
   (data-offset uint16  :offset 96)
   (elt-count   uint32  :offset 112 :size 15)
   (inlined?    uint8   :offset 127 :size 1)
   )
  :flag-assert #x900000010
  )
```

- A field located in the upper 64 bits is accessed through `pcpyud dest src r0` followed by the usual bit shift operations.
- A field located at bit 64 *and* with size 32 is accessed through `pextuw dest r0 src`
- 128-bit copy is done through `por dest src r0`

**Comment by xTVaser** [comment]
Examples of unsupported `POR` instructions can also be found in:
- hud
- settings

**Comment by water111** [comment]
Fields in the lower 64 bits seem to be treated just like 64-bitfields.

In `method 2 vec4s` a field at bit 64 with size 32 is accessed with:
```
    pcpyud v1, gp, r0
    sllv t0, v1, r0 
```
and not `pextuw`.  I am not sure what the difference here is.  In `res` it definitely used `pextuw` for accessing the `elt-type` field of `res-tag`.

**Comment by water111** [comment]
I looked at all of the `pextuw`s in the game, and it's only used with the `r0` in `res` and `actor-link`, where it's also accessing a `res-tag`.  Maybe this was a macro?   The decompiler should support both `pextuw` and `pcpyud/sllv` for accessing a field like this.

**Comment by ManDude** [comment]
It might be because `type` is a reference (32-bit value) and thus it makes sense to copy it using the operation that outputs a 32-bit vlue?

**Comment by water111** [comment]
That's a good point.  Both examples are 32 bit values, but the `pextuw` one should be zero extended and the `sllv` one should be sign extended.  (The GOAL compiler sign extends 32-bit floats for some reason).

**Comment by water111** [comment]
Most of the 128-bit bitfield stuff should work. `POR` is recognized as a move for 128-bit variables and bitfield extraction should work in all cases.  I'm leaving this open for now because there will probably be other tricks that we haven't encountered yet.

**Comment by water111** [comment]
see `res-lump` method 15 for some settings stuff.

**Comment by water111** [comment]
`sound-name=` isn't extracting upper 64 bit fields correctly.

**Comment by water111** [comment]
There may be stuff we haven't seen yet, but for now `res` and `gsound` both pass the offline tests.  Setting bitfields is a bit ugly looking in the output (during a set, it copies the 128-bit bitfield to another variable, if it is valid to do so), but it at least works.
