### ISSUE TITLE
[decompiler] Support define-perm

### ISSUE THREAD

**Issue by water111** [water111/jak-project#451]
This should be detected by the top level stuff.

**Comment by ManDude** [comment]
The `define-perm` macro we have uses `if`, but some files have `when` and others have `if`. Not a big deal?

**Comment by water111** [comment]
Internally `when` is just an `if` without an `else` where the body is a single form, so it won't be an issue.  Where do you see one with a `when`? I would expect them to be `if`s but i might be missing something.

**Comment by water111** [comment]
There's something going wrong with this logic:
https://github.com/water111/jak-project/blob/21fefa0aaa5b502b44bf5a35d9574e76d3e01de6/decompiler/IR2/Form.cpp#L1128

yet in `target-h` it picks `when`.
```lisp
(when (or (not *sidekick*) (zero? *sidekick*))
  (set! *sidekick* #f)
  )
```

maybe there's a dead set that triggers this check but doesn't print? I forget how that works...

**Comment by ManDude** [comment]
`target-h`:
```lisp
(when (or (not *target*) (zero? *target*))
  (set! *target* #f)
  )
```
```lisp
(when (or (not *sidekick*) (zero? *sidekick*))
  (set! *sidekick* #f)
  )
```

`main-h`:
```lisp
(when (or (not *dproc*) (zero? *dproc*))
  (set! *dproc* #f)
  )
```

`texture`:
```lisp
(when (or (not *font-texture*) (zero? *font-texture*))
  (set! *font-texture* #f)
  )
```

`game-info-h`:
```lisp
(set! gp-0 (when (or (not *game-info*) (zero? *game-info*))
           (set!
            gp-0
            (new 'static 'game-info :mode 'debug :current-continue #f)
            )
           (set! (-> gp-0 fuel-cell-time) (new 'global 'boxed-array uint64 116))
           (set!
            (-> gp-0 enter-level-time)
            (new 'global 'boxed-array uint64 32)
            )
           (set! (-> gp-0 in-level-time) (new 'global 'boxed-array uint64 32))
           (set! *game-info* gp-0)
           gp-0
           )
  )
```
