### ISSUE TITLE
[decompiler] improve use/def counting on nested conditionals returning values

### ISSUE THREAD

**Issue by water111** [water111/jak-project#454]
Happens on a `def` in `file-info-correct-version?` for example.

**Comment by xTVaser** [comment]
`(method 9 vol-control)` in `vol` seems to have this problem as well

**Comment by ManDude** [comment]
`toggle-pause`

**Comment by xTVaser** [comment]
`cam-slave-get-vector-with-offset` in `camera`

**Comment by water111** [comment]
` debug-menu-func-decode` in `menu` (a short one!)

**Comment by water111** [comment]
Believed fixed in https://github.com/water111/jak-project/pull/629, will reopen if it comes up again.
