### ISSUE TITLE
[opengoal] Allow more than two inputs for `+` and `*` operators

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#464]
Afaik this is a standard thing in most other lisp implementations, and it could be used to make some of our code look a bit nicer.

**Comment by water111** [comment]
It should work correctly in the compiler already.

We already have some stuff in the decompiler that nests automatically, like the `->` operator, that part isn't hard.  The annoying part is getting the casts right. I do want to clean that up a lot to hopefully make features like this much easier to implement.  Now that we have lots of test cases, I think this should be easier.

**Comment by water111** [comment]
It was added for `+` for integers.

I will add `+` and `*` for floats soon.
