### ISSUE TITLE
[GOAL] taking the address of a stack spilled variable

### ISSUE THREAD

**Issue by water111** [water111/jak-project#471]
I was wrong - it turns out you can take the address of a variable spilled to the stack. It's done in `(method 0 fact-info)`.

This seems like it won't be so bad to support in the decompiler.  We can upgrade the stack-vars file to support this. Also should clear up "stack structure" vs. "stack variable".

In OpenGOAL we don't have any support for this yet.  I think there are two parts to this:
- Have a way to tell the compiler that a variable should be spilled onto the stack.
- Allow taking the address of one of these.

**Comment by ManDude** [comment]
Also in `(method 18 res-lump)` and `(method 21 res-lump)`

**Comment by xTVaser** [comment]
occurs when calling one of `res-lump`'s methods in `entity-actor-lookup` in `actor-link-h`

**Comment by water111** [comment]
This was added in https://github.com/water111/jak-project/pull/554 and seems to work pretty well.
