### ISSUE TITLE
[decompiler] handle `case`

### ISSUE THREAD

**Issue by water111** [water111/jak-project#477]
I think GOAL's `case` would also let you have multiple possibilities and use an `or` automatically.

**Comment by water111** [comment]
`case` is slightly different than I thought.

In normal Common Lisp, the elements aren't evaluated and are treated as constants.  So something like:

```lisp
(let ((x 'foo))
  (case x
    (foo (format #t "hi~%")) ;; foo isn't evaluated, so it's a symbol
    )
  )
```
will print `hi`.

You can also put multiple things in a case, and there's evidence that GOAL code does this:

```lisp
(let ((x 'foo))
  (case x
    ((foo bar) (format #t "hi~%")) ;; runs if x = 'foo or x = 'bar
    )
  )
```

But, in GOAL, you could imagine that you have
```lisp
(defenum foo
  (bar 1)
  )
```
which would make `(foo bar)` ambiguous. Is it a list of two symbols, or the enum constant?


I think most of these ambiguities could be solved with a slightly different format, where the key _is_ evaluated, and you're always required to put the keys in a list, even if there's only one

For a single symbol, it would look like this:
```lisp
(let ((x 'foo))
  (case x
    (('foo) (format #t "hi~%"))
    )
  )
```

Two symbols:
```lisp
(let ((x 'foo))
  (case x
    (('foo 'bar) (format #t "hi~%"))
    )
  )
```

Enum:
```lisp
(let ((x 'foo))
  (case x
    (((foo bar)) (format #t "hi~%"))
    )
  )
```

Two enums:
```lisp
(let ((x 'foo))
  (case x
    (((foo bar) (foo bar2)) (format #t "hi~%"))
    )
  )
```

**Comment by ManDude** [comment]
This can probably be closed for now. We just went with forcing the condition as a list at all times.

**Comment by ManDude** [comment]
Oh wait, I misread the title. This is for the decompiler, not compiler.

**Comment by water111** [comment]
lol me too

**Comment by water111** [comment]
Added in https://github.com/water111/jak-project/pull/687
