### ISSUE TITLE
[Decompiler] Handle casting `0` automatically in early returns

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#489]
If a function has an early return (thankfully, this is rare so far!) its typically because it fails and it returns `0`.  This is the convention (so far) and it needs to be cast to the correct type.

An example can be found in `aligner-h` where the `(the-as align-control 0` had to be manually added:

```lisp
;; definition for method 0 of type align-control
;; INFO: Return type mismatch object vs align-control.
(defmethod
  new
  align-control
  ((allocation symbol) (type-to-make type) (arg0 process))
  (local-vars (pp process))
  (let
   ((obj
     (object-new allocation type-to-make (the-as int (-> type-to-make size)))
     )
    )
   (if (zero? obj)
    (return (begin
             (let ((t9-1 (the-as (function object object) enter-state))
                   (a0-1 "memory")
                   )
              (set!
               (-> pp next-state)
               (the-as state process-drawable-art-error)
               )
              (t9-1 a0-1)
              )
             (the-as align-control 0)
             )
     )
    )
   (set! (-> obj process) arg0)
   (the-as align-control (the-as object obj))
   )
  )
```

**Comment by water111** [comment]
A few related issues:
- the double cast at the end
- `str-load-status` thinks the return type is `structure` for some reason.

**Comment by water111** [comment]
The `rewrite_to_get_var` function was accidentally removing casts.
The double cast at the end was due to the function return value cast looking at register types even when the result was a variable.
The return type being `structure` in `str-load-status` was due to a bad type cast.
