### ISSUE TITLE
[tooling] EE Memory analysis tool feature requests

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#534]
1. It would be nice if the tool instead of always generating a single output for each EE dump, could be given a previous input file to append to.  I imagine situations where you'd want to take multiple save-states over the course of a session and amalgamate the type info all into one place.  Right now that is a little cumbersome.
2. Supporting arrays would be very helpful
3. Resolving nested types would be a nice to have.

**Comment by water111** [comment]
1. Maybe the way to go here is to output to JSON, and then have a mode to convert one or more JSON outputs into a single easy-to-read output, merging them as needed.
2. This should be easy for arrays of basics. Inline arrays would be harder but it might be possible to identify the first element.
3. Agreed. This could let us find structures that can't be found by the basic scan, which might give us a lot more information.  The challenge here is to not get confused by following garbage pointers when we've misidentified basics, and not to get stuck in loops when we have circular references.

**Comment by water111** [comment]
Also, do you have an example for 2?

**Comment by water111** [comment]
`sel-menu` in `debug-menu-context` is an array of basics.

**Comment by water111** [comment]
#562 will add support for arrays of basics, like `(array-of-basics basic 10)`.

**Comment by water111** [comment]
1. Was added by Vaser a long time ago, seems to be working great
2. Arrays are supported now
3. #797 is the best thing I could come up with that works in general. If there are more specific cases, we can always write more specific tools.
