### ISSUE TITLE
[opengoal] "Inconsistent type" error should highlight the differences

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#593]
Right now it just prints the two types, which isn't helpful if they're both rather large and the difference is a single word.

**Comment by water111** [comment]
Now it will print diffs like this:
```
Diff:
Method def 2 (dummy-11/dummy-11):
type: (function _type_ none) vs. (function none)

Diff:
field 0 (volume-type/volume-type):
type: string vs. basic
```

It can't print this info for totally different type "kinds", like where one is a bitfield and the other is a structure, but these should be obvious.
