### ISSUE TITLE
[decompiler] Support setting static fields to a `type`

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#612]
This can be seen in `entity-table` - https://github.com/xTVaser/jak-project/commit/1b0384ddb5b3627c988d0ebcf16eb6019fecfa4f

```nasm
    .type entity-info
L9:
    .type target-start
    .word L30
    .empty-list
    .symbol *16k-dead-pool*
    .word 0x400
    .word 0x0
    .word 0x0
    .type entity-info
```

Results in `Field ptype in type entity-info offset 4 did not have a proper reference`

**Comment by water111** [comment]
feature added in https://github.com/water111/jak-project/pull/613
