### ISSUE TITLE
[decompiler] CFG infinite loop not working when it requires nesting stuff inside the loop

### ISSUE THREAD

**Issue by water111** [water111/jak-project#619]
Infinite loops are supported, but they expect to be a single vertex that branches to itself. There's only one example, `looping-code`, and it happens to be a single vertex to begin with.  It seems like the current implementation doesn't generalize to more complicated cases.

For example in `(method 18 tracking-spline)`, it ends up getting to the point where the infinite loop is two vertices:
![image](https://user-images.githubusercontent.com/48171810/122854336-92f5f800-d2e1-11eb-8b94-ba295c2e32af.png)

but fails to recognize that as an infinite loop. I _think_ it should be safe to merge the two blocks in the loop into a single one as a normal sequence building operation, with an edge that points to itself.   And then it would be recognized as a normal infinite loop. 

In fact, I am not sure why this doesn't get turned into a sequence...

**Comment by water111** [comment]
Previously, we intentionally didn't allow vertices like CONDWE19/Block 10 to turn into a sequence. The reason for this seems to be to get nicer formatting in certain `until` loops by keeping the condition as small as possible and letting expression propagation take care of making it bigger if needed.

This is easy to work around by only building these sequences if the only other option is a goto.  After doing this, the function has the CFG that makes sense.  But, the register -> variable pass is totally wrong.  There are example of both types of errors: splitting when it shouldn't (correctness issue!), and failing to split.

**Comment by water111** [comment]
Both the variable bugs are related to not properly handling the connection between function arguments and their variable.  There has historically been some issues with functions that ignore an argument and reuse that register for a very similar reason. It is time to fix this system.

**Comment by xTVaser** [comment]
Another failure to recognize dead code in `(anon-function 1 cam-combiner)` - https://github.com/water111/jak-project/pull/621/commits/aef322dfe6cdf1fe5bef49ec8bc764896952845d

**Comment by water111** [comment]
These seem to work now.
