### ISSUE TITLE
The pretty printer doesn't work very well

### ISSUE THREAD

**Issue by water111** [water111/jak-project#63]
Eventually we will look at the output of the decompiler a lot, which will go through the pretty printer.  The pretty printer output is better than nothing but still has some issues. Examples of running the pretty printer on existing code:
```
  (defun type-type? ((a type) (b type))
   "is a a type (or child type) of type b?"
   (until
    (eq? a object)
    (if (or (eq? a b) (zero? a)) (return-from #f #t))
    (set! a (-> a parent))
    )
   #f
   )

  (defmethod
   new
   inline-array-class
   ((allocation symbol) (type-to-make type) (cnt int))
   "Create a new inline-array.  Sets the length, allocated-length to cnt.  Uses the mysterious heap-base field
  of the type-to-make to determine the element size"
   (let*
    ((sz (+ (-> type-to-make size) (* (-> type-to-make heap-base) cnt)))
     (new-object (object-new (the int sz)))
     )
    (unless
     (zero? new-object)
     (set! (-> new-object length) cnt)
     (set! (-> new-object allocated-length) cnt)
     )
    new-object
    )
   )

  (defun mem-set32! ((dst pointer) (value int) (n int))
   "Memset a 32-bit value n times.  Total memory filled is 4 * n bytes."
   (let
    ((p (the pointer dst)) (i 0))
    (while
     (< i n)
     (set! (-> (the (pointer int32) p) 0) value)
     (&+! p 4)
     (+1! i)
     )
    )
   dst
   )
  )

```

Some of these could be solved by adding special cases for certain key words/structures, but the fundamental problem may be that my pretty printer algorithm isn't very good.  If this starts to become a more serious issue, we should investigate other options. I think even a "perfect" printing algorithm that found the optimal pattern of inserting line breaks would not do the right thing - there are lots of cases where line breaks are inserted to make the code more readable even if they aren't needed.  Maybe the decompiler needs to give the printer hints on where lines should be broken. For instance, the body of a `let` should always be on the line after a let.

**Comment by jsjolen** [comment]
You could always just use whatever Emacs does to pretty-print elisp as the output.

If you really want to build your own pretty printer then why not just have something which recurs over the shape of the `Object` as if it was conforming to the GOAL grammar? You don't need to know the whole grammar, but all this stuff with converting the AST to a `std::vector<FormToken>*` makes you lose context which you need for proper pretty printing.

**Comment by water111** [comment]
I think that's a really good point.  I think @xTVaser looked into using the pretty printer from emacs in some way, and it seemed possible, which seems better than writing our own if possible.  If we do end up writing our own GOAL pretty printer, I agree that we should have it be aware of the GOAL forms.

The current pretty printer works reasonably well for printing out intermediate results from the decompiler for debugging, but it's not going to be good for the final output.

**Comment by jsjolen** [comment]
Could probably just execute this  `emacs --batch --eval="(pp (read \"lispexpr\"))"` with `popen` as in: https://stackoverflow.com/questions/478898/how-do-i-execute-a-command-and-get-the-output-of-the-command-within-c-using-po

But then I guess you're limited to Linux for pretty-printing.

**Comment by xTVaser** [comment]
I tried your suggestion, that works well for single expressions and i bet there is a way to get it to work in windows, its unfortunate that emacs would become a dependency for the REPL though.

For our use-case, pretty-printing/formatting seems to be more important for ingesting the large amounts of code coming out from the decompiler and less so for pretty-printing individual forms.  The problem is current code formatting tooling either require packages and need to be wrapped by an emacs script https://github.com/tuhdo/semantic-refactor or does not seem to work out of the box at all (and lacks documentation) https://github.com/eschulte/lisp-format

So for pretty-printing an entire file, `pp` seems to be inadequate, it only is concerned with the first complete form, and drops comments:

```
emacs -batch .\goal_src\goal-lib.gc --eval '(pp (read (buffer-string)))' > .\goal_src\goal-lib-test.gc
```
> only pretty-prints the first form / removes comments.

So semantic-refactor seems to still remain the best option, with the challenge to overcome: figure out how to use a MELPA package in batch mode.

**Comment by water111** [comment]
I think the pretty printer is now good enough. If we ever want better formatting, I think it would be better to make a formatting tool instead of messing with the pretty printer.

Example output:
```
;; definition for function mem-set32!
(defun mem-set32! ((dst pointer) (size int) (value int))
  (let ((result dst))
   (dotimes (i size)
    (set! (-> (the-as (pointer int32) dst)) value)
    (&+! dst 4)
    (nop!)
    )
   result
   )
  )
  ```
