### ISSUE TITLE
[compiler] Support an explicit `:else` in `defenum` definition

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#669]
Rather than doing something like:
```lisp
(defenum task-status
  :type uint64
  (invalid 0)
  (unknown 1)
  (need-hint 2)
  (need-introduction 3)
  (need-reminder-a 4)
  (need-reminder 5)
  (need-reward-speech 6)
  (need-resolution 7)
  (*unknown* 999999)
  )
```

which still leaves gaps,
it would be nice have to something like:

```lisp
(defenum task-status
  :type uint64
  (invalid 0)
  (unknown 1)
  (need-hint 2)
  (need-introduction 3)
  (need-reminder-a 4)
  (need-reminder 5)
  (need-reward-speech 6)
  (need-resolution 7)
  :else *unknown*
  )
```

**Comment by ManDude** [comment]
I don't think this is necessary. They most certainly never had an `*unknown*` in their enums. The `enum->string` functions were most likely generated with the help of a macro that would iterate through each enum value and add the proper cond, then just adds the else at the end of it all.

**Comment by water111** [comment]
Eventually I will implement https://github.com/water111/jak-project/issues/598 and then somebody can write a macro to autogenerate these enum -> string methods.
