### ISSUE TITLE
[compiler] stack spill regs can exhaust in rare cases, stack spilling happens too often in general

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#727]
see `set-display-gs-state-offset` in [here](https://github.com/water111/jak-project/pull/725/commits/ebc283e027a9ed9b3f58454c4df56a607d09090a)

**Comment by water111** [comment]
Currently we generate 22757 stack load/stack store instructions in the whole game.  It's expected that we will have more than the original (x86 has fewer registers), but this is really bad.
