### ISSUE TITLE
[Low-Priority] - Create documentation on github pages once the Compiler/Decompiler stabilizes

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#76]
Once the bulk of the work on the compiler/decompiler is finished (going to be a while).  It might be a nice idea to wrap up the documentation on a nice frontend.  https://github.com/slatedocs/slate seems to make some good looking stuff.

**Comment by water111** [comment]
I think we can document quite a bit of the compiler stuff at this point, and it's probably good to get started early.  I started on it here: https://github.com/water111/jak-project/blob/master/doc/goal_doc.md but I still have quite a bit left to do.

**Comment by xTVaser** [comment]
Yup, the markdown documentation for now is more than enough for our purposes, so we should keep building that out as we move along

**Comment by water111** [comment]
closing, there's a newer issue with the same thing here: https://github.com/water111/jak-project/issues/371
