### ISSUE TITLE
Move file I/O utilities to a single library

### ISSUE THREAD

**Issue by water111** [water111/jak-project#8]
Because this repo started as a few separate projects, there is some duplicated code for reading/writing files in `decompiler/util/FileIO.h` and `goal/util/file_io.h`.  These should be moved to a single common library in `common/util` that should probably get its own `CMakeLists.txt` file.

The code for `Timer` is also duplicated a bunch and could go in this library as well.

**Comment by water111** [comment]
This also should replace `fake_iso.txt` with `fake_iso.json` and have a function to generate fake iso paths.

**Comment by xTVaser** [comment]
On the topic of JSON support, and seeing the comment in the README's todo about wanting to keep comments.  We can use this https://github.com/andrew-d/json-strip to strip the comments before passing it to nholman's
