### ISSUE TITLE
[compiler] `declare-type` does not seem to inherit methods properly

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#838]
Example - https://github.com/water111/jak-project/blob/master/goal_src/levels/village3/miners.gc#L21-L30

If I were to not manually re-organize this file, a behavior for `minershort` comes at the very top of the file, and it uses a method that is inherited from `process-taskable`:

```lisp
(defbehavior miners-anim-loop minershort ()
  (when (!= (if (> (-> self skel active-channels) 0)
             (-> self skel root-channel 0 frame-group)
             )
         (get-art-elem self)
         )
```

even if i setup a `(declare-type minershort process-taskable)` i still get the following error:

> No method or function named get-art-elem for type minershort
Form:
(get-art-elem self)
Location:
goal_src/levels/village3/miners.gc, line: 19
         (get-art-elem self)

**Comment by water111** [comment]
Fixed in https://github.com/water111/jak-project/pull/836, I undid your reordering in miners.
