### ISSUE TITLE
[decompiler] say what object file is currently being worked on

### ISSUE THREAD

**Issue by ManDude** [water111/jak-project#889]
Often times the decompiler will crash without warning but with no indication of the cause or even which file it crashed on. Makes it very difficult to debug quickly.

**Comment by ManDude** [comment]
sticking a print in `for_each_obj` does the job but also spams the console ridiculously hard... need something more elegant

**Comment by doctashay** [comment]
#890 will send this info to the decompiler.log file in a much more elegant fashion, if it is too verbose we can always log it to a separate file

**Comment by ManDude** [comment]
fixed(?) in #895
