### ISSUE TITLE
[decomp] `collectables` issues

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#927]
There are a few issues in collectables

- process-tree's 10 method pparently has a 3rd arg -- im doubtful
- set-to-run function fails
> ;; WARN: Expression building failed: In birth-pickup-at-point: Unhandled branch delay in BranchElement::push_to_stack: (bl! (not v1-1) L76 (no-delay!))
- weird code in method 21 eco-collectable

**Comment by ManDude** [comment]
"fixes"
