### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by mattbruv** [water111/jak-project#980]
Do you all have a discord server (preferably) or some other way of communication about the project? I would absolutely LOVE to start contributing to this project and learning the ropes. A discord server would be perfect for this type of project if there isn't one already.

**Comment by water111** [comment]
yep, we've got a discord server: https://discord.gg/E7yFpd6w9G
I also added it to the readme - I think there's a link buried in an issue somewhere but it's hard to find that.
